#
#   ${project.name} v${project.version} by RezzedUp
#
#   ---
#
#   This plugin *requires* DiscordSRV in order to access Discord.
#   It will, however, work just fine in-game regardless whether DiscordSRV is installed or not.
#   
#   ---
#
#   Installation (Discord Setup):
#
#   - 1) Install this plugin and DiscordSRV
#
#   - 2) Add a "staff-chat" channel to DiscordSRV's config
#
#     EXAMPLE:
#         # Channel links from game to Discord
#         # Replace '00000000000' with your channel's id
#         Channels: {"global": "00000000000", "staff-chat": "00000000000"}
#         #                                        ^              ^
#         #                         All staff chat messages will be sent to this channel.
#
#     IMPORTANT NOTE:
#         The channel's name can be anything on discord (since DiscordSRV uses its channel id) ...
#         However, it MUST be called "staff-chat" in the config.
#         **This is very important!**
#
#   - 3) Restart the server
#
#   - 4) Give staff ranks permission to use the staff chat: 'staffchat.access'
#
#   ---
#
#   This config can be reloaded in-game with: '/managestaffchat reload'
#   (Be sure to give yourself permission to manage the staff chat with: 'staffchat.manage')
#

#
#   *If* PlaceholderAPI is installed, both in-game and discord formats will also utilize them.
#   That plugin is not necessary for the existing placeholders in this config, however.
#

in-game-message-format: "&d(&5&l&oStaff&d) %name%&7:&f %message%"
discord-message-format: "&9&lDiscord &f-> &d(&5&l&oStaff&d) %name%&7:&f %message%"

#
#   Automatic staff-chat toggle messages.
#

enable-staff-chat: "&d(&5&l&oStaff&d) &2->&a &nEnabled&a automatic staff chat"
disable-staff-chat: "&d(&5&l&oStaff&d) &4->&c &nDisabled&c automatic staff chat"

#
#   If a staff member leaves the server with automatic staff chat enabled,
#   this plugin will remember and remind them upon joining back.
#   All toggles will be disabled if this plugin is unloaded (e.g. if the server restarts).
#

notify-staff-chat-enabled-on-join: true
staff-chat-enabled-notification: "&d(&5&l&oStaff&d) &2->&a Automatic staff chat is &nenabled"
